#!/usr/bin/env /home/proxpxd/.conda/envs/common311/bin/python3.11

from __future__ import annotations

import json

from actions import *
from utils import Task
from common import perform

raw: Task = json.loads(sys.stdin.readline())
perform(raw, actions=[
    Autotag(),
    ReverseDependency(),
    # RecurDependencies(),
    MarkForDependencies(),
])
sys.exit(0)
