#!/usr/bin/env /home/proxpxd/.conda/envs/common311/bin/python3.11

from __future__ import annotations

import json
import sys

from actions import *
from utils import Task
from common import perform

old_task: Task = json.loads(sys.stdin.readline())
new_task: Task = json.loads(sys.stdin.readline())
perform(new_task, old_task, actions=[
    Autotag(),
    ReverseDependency(),
    # RecurDependencies(),
    MarkForDependencies(),
])
sys.exit(0)
